from selenium.webdriver.common.by import By

BASE_URL = "https://www.booking.com"
ACCEPT_COOKIE_BUTTON = (By.ID, 'onetrust-accept-btn-handler')
CURRENCY_MENU = (By.XPATH, '//button[@data-testid="header-currency-picker-trigger"]')
CURRENCY_VALUE = (By.XPATH, '//h3[contains(text(),"Suggested for you")]/following-sibling::div//span[contains(text(),"Dollar")]//parent::div//parent::div//parent::button')
CLOSE_ECONOMY_MEMBER = (By.CSS_SELECTOR, "#b2indexPage > div.b9720ed41e.cdf0a9297c > div > div > div > div.dd5dccd82f > div.ffd93a9ecb.dc19f70f85.eb67815534.e91f709929 > div > button")
CURRENCY_SELECTED_VALUE = (By.XPATH, '//div[@class="aca0ade214 aaf30230d9 c2931f4182 e7d9f93f4d faf8b5d9a5"]//button[@data-testid="header-currency-picker-trigger"]/span[@class="e4adce92df"]')
LANGUAGES_MENU = (By.XPATH, '//span/button[@data-testid="header-language-picker-trigger"]')
LANGUAGE_VALUE = (By.XPATH, '//h3[contains(text(),"Suggested for you")]//following-sibling::div//span[contains(text(),"Rom")]//parent::div//parent::div//parent::button')
LANGUAGE_SELECTED_VALUE = (By.XPATH, '//button[@data-testid="header-language-picker-trigger"]')
PLACE_TO_GO = (By.NAME, 'ss')
CLICK_FIRST_RESULT = (By.XPATH, '//div[text()="Paris"]')
CHOSEN_PLACE = (By.XPATH, '//div[text()="Paris"]')
CLICK_CHECK_IN_DATE = (By.XPATH, '//span[@class="b6dc9a9e69 a804864eef e6c50852bd b8c9de5937"]')
DATE_CHECK_IN = (By.XPATH, '//span[@data-date="2023-09-10"]')
DATE_CHECK_OUT = (By.XPATH, '//span[@data-date="2023-09-15"]')
REGISTER_MAIN_BUTTON = (By.LINK_TEXT, "Register")
REGISTER_EMAIL_INPUT = (By.XPATH, '//input[@type="email"]')
REGISTER_CONTINUE_WITH_EMAIL_BUTTON = (By.XPATH, '//button[@type="submit"]')
CREATE_ACCOUNT = (By.XPATH, '//button[@type="submit"]')
WRONG_EMAIL_ADRESS = (By.CLASS_NAME, "Iiab0gVMeWOd4XcyJGA3 wPxWIS_rJCpwAWksE0s3 Ut3prtt_wDsi7NM_83Jc TuDOVH9WFSdot9jLyXlw EJWUAldA4O1mP0SSFXPm whxYYRnvyHGyGqxO4ici")
REGISTER_PASSWORD_INPUT = (By.XPATH, '//*[@id="password"]')
REGISTER_PASSWORD_CONFIRM = (By.NAME, "confirmed_password")
WRONG_PASSWORD_ERROR = (By.ID, "confirmed_password-note")
SIGN_IN_MAIN_BUTTON = (By.XPATH, '//a[@data-testid="header-sign-in-button"]')
PRESS_SIGNIN_BUTTON = (By.XPATH, '//button[@type="submit"]')
CLICK_ADULTS_CHILDS_ROOM = (By.CLASS_NAME, "d67edddcf0")
CLICK_ADDED_ADULTS = (By.XPATH,'//*[@id="indexsearch"]/div[2]/div/form/div[1]/div[3]/div/div/div/div/div[1]/div[2]/button[2]')
UPDATE_VALUE_ADULTS = (By.XPATH, '//*[@id="indexsearch"]/div[2]/div/form/div[1]/div[3]/div/div/div/div/div[1]/div[2]/span')
CLICK_ADDED_CHILDS = (By.XPATH,'//*[@id="indexsearch"]/div[2]/div/form/div[1]/div[3]/div/div/div/div/div[2]/div[2]/button[2]')
CLICK_FIRST_CHILD = (By.XPATH, '//*[@id="indexsearch"]/div[2]/div/form/div[1]/div[3]/div/div/div/div/div[3]/div[1]')
STATUS_DROPDOWN = (By.CSS_SELECTOR, '#\:r13\: > option:nth-child(14)')
DROPDOWN_AGE_NEEDED = (By.XPATH,'//select[@name="age"]')
SEARCH_DATA = (By.XPATH,'//button[@data-testid="occupancy-config"]')
FIND_GETAWAY_DEALS = (By.XPATH,'//a[@data-testid="herobanner-cta"]')